apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  containers:
    - env:
        - name: WORDPRESS_DB_PASSWORD
          value: netapp01
      image: wordpress
      name: wordpress
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-persistent-storage
  volumes:
    - name: wordpress-persistent-storage
      persistentVolumeClaim:
        claimName: wordpress-disk
