apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-thick
provisioner: netapp.io/trident
parameters:
  backendType: "ontap-nas"
  provisioningType: "thick"
  snapshots: "true"