apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-thin
provisioner: netapp.io/trident
parameters:
  backendType: "ontap-nas"
  provisioningType: "thin"
  snapshots: "true"